version: "2.3"
services:
  notebook:
    runtime: nvidia
    container_name: od_container
    labels:
      description: object_detection API Nvidia GPU Python 3 using Jupyter Notebooks
      name: jupyter_notebook 
    ports:
      - "8888:8888"
    volumes:
      - /home/shogun/Desktop/Projetos/Python/ObjectDetection/workspace:/usr/src/object_detection/workspace
    build: . 
    command: ["jupyter","notebook","--port=8888","--no-browser","--ip=0.0.0.0","--allow-root"]